# Generated by Django 4.2.2 on 2023-06-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bid_bid_amount_bid_bidder_bid_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
