# Generated by Django 4.2.2 on 2023-06-20 14:07

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_starting_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='deadline',
            field=models.DateTimeField(default=auctions.models.get_default_deadline),
        ),
    ]
